import type { CreditNote, Invoice } from '../../shared/types';

/**
 * A credit note has the same shape of content as an invoice, so the invoice document draws it directly: the title, the number label
 * and the missing payment details are decided by `variant="credit-note"`. It is never owed or paid, so its status is neutral.
 */
export function creditNoteAsInvoice(n: CreditNote): Invoice {
  return {
    id: n.id,
    number: n.number,
    type: n.type,
    customerId: n.customerId,
    buyerName: n.buyerName,
    issueDate: n.issueDate,
    dueDate: null,
    totalPaise: n.totalPaise,
    paidPaise: 0,
    status: 'unpaid',
    deliveryStatus: 'none',
    shipTo: null,
    transport: '',
    trackingNo: '',
    deliveredOn: null,
    series: '',
    seller: n.seller,
    branding: n.branding,
    buyer: n.buyer,
    placeOfSupply: n.placeOfSupply,
    gstRatePercent: n.gstRatePercent,
    pricesIncludeGst: n.pricesIncludeGst,
    intraState: n.intraState,
    subtotalPaise: n.subtotalPaise,
    lineDiscountPaise: n.lineDiscountPaise,
    credits: [],
    creditedPaise: 0,
    taxByRate: n.taxByRate,
    discountPaise: 0,
    taxablePaise: n.taxablePaise,
    cgstPaise: n.cgstPaise,
    sgstPaise: n.sgstPaise,
    igstPaise: n.igstPaise,
    roundOffPaise: n.roundOffPaise,
    notes: '',
    lines: n.lines.map((l) => ({
      id: l.id,
      variantId: l.variantId ?? '',
      designName: l.designName,
      color: l.color,
      size: l.size,
      sku: l.sku,
      hsn: l.hsn,
      qty: l.qty,
      unitPricePaise: l.unitPricePaise,
      amountPaise: l.amountPaise,
      discountPaise: l.discountPaise,
      ratePercent: l.ratePercent,
      note: '',
      taxablePaise: l.taxablePaise,
      taxPaise: l.taxPaise,
    })),
    payments: [],
    cancelledAt: null,
    cancelReason: '',
    createdAt: n.createdAt,
  };
}
